import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import { ThirdwebProvider } from "thirdweb/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className} bg-yellow`}>
        <ThirdwebProvider>
          <Navbar />
          {children}
          <Image
            src="/arcade-machine-bg.svg"
            alt="alt"
            width={1000}
            height={1000}
            className="fixed right-0 bottom-0 w-[30rem] -z-10 opacity-70"
          />
        </ThirdwebProvider>
      </body>
    </html>
  );
}
